### ISSUE TITLE
Unable to set colorscheme

### ISSUE THREAD

**Issue by samokosik** [arcticicestudio/nord-xfce-terminal#12]
Hello, I put the nord.theme to desired folder but I see no theme in the presets:
![image](https://user-images.githubusercontent.com/73645764/147822511-c32fb8a1-2df0-472f-ab42-4019e6abe791.png)
Any help?
Thank you

**Comment by duffydack** [comment]
![scr-2021-12-31_12-09-05](https://user-images.githubusercontent.com/41839511/147823074-a730907a-f425-4bc7-b7fc-4fd07a2d8f17.png)

Works for me™ - verified the contents of it, to make sure it's correct?

**Comment by samokosik** [comment]
Yes, it behaves quite strangely

**Comment by arcticicestudio** [comment]
Hi @samokosik :wave:
Like @duffydack suggested can you please post the output of the file, e.g. by running `cat ~/.local/share/xfce4/terminal/colorschemes/nord.theme` or open it in your favorite text editor.
If you downloaded the file by using the “Save As…“ context menu function of your browser on the link from the repository README you'll simply end up with the HTML page of GitHub. If so this is not the way how it should be saved since it is only a link to the blob and you need to either copy the content from the page or use the `raw` domain, e.g. https://raw.githubusercontent.com/arcticicestudio/nord-xfce-terminal/develop/src/nord.theme

**Comment by arcticicestudio** [comment]
@samokosik have you been able to fix the problem? Without the suggestions from my previous content we're not able to analyze the problem in more detail.

**Comment by samokosik** [comment]
Yes, I managed, thank you
